const WORDS = [
  { sumerian: "a", unicode: "\u{12000}", english: "water" },
  { sumerian: "izi", unicode: "\u{12248}", english: "fire" },
  { sumerian: "mushen", unicode: "\u{12137}", english: "bird" },
  { sumerian: "erin", unicode: "\u{1209F}", english: "people" },
  { sumerian: "inim", unicode: "\u{12157}", english: "word" },
  { sumerian: "ki", unicode: "\u{121A0}", english: "place" },
  { sumerian: "an", unicode: "\u{1202D}", english: "sky" },
  { sumerian: "ĝesh", unicode: "\u{12111}", english: "tree" },
  { sumerian: "gi", unicode: "\u{12100}", english: "reed" },
  { sumerian: "ab", unicode: "\u{1200A}", english: "father" },
  { sumerian: "ak", unicode: "\u{1201D}", english: "to do" },
  { sumerian: "anshe", unicode: "\u{12032}", english: "donkey" },
  { sumerian: "arad", unicode: "\u{12034}", english: "slave" },
  { sumerian: "da", unicode: "\u{12055}", english: "line" },
  { sumerian: "dam", unicode: "\u{1206E}", english: "spouse" },
  { sumerian: "dara", unicode: "\u{12071}", english: "red" },
  { sumerian: "dab", unicode: "\u{12073}", english: "to seize" },
  { sumerian: "dim", unicode: "\u{12074}", english: "post" },
  { sumerian: "mun", unicode: "\u{12075}", english: "salt" },
  { sumerian: "du", unicode: "\u{1207A}", english: "to go" },
  { sumerian: "dub", unicode: "\u{1207E}", english: "tablet" },
  { sumerian: "e", unicode: "\u{1208D}", english: "house" },
  { sumerian: "eden", unicode: "\u{12094}", english: "back" },
  { sumerian: "en", unicode: "\u{12097}", english: "lord" },
  { sumerian: "ga", unicode: "\u{120B5}", english: "milk" },
  { sumerian: "ama", unicode: "\u{120BC}", english: "mother" },
  { sumerian: "gaba", unicode: "\u{120EE}", english: "chest" },
  { sumerian: "gal", unicode: "\u{120F2}", english: "big" },
  { sumerian: "ninda", unicode: "\u{120FB}", english: "bread" },
  { sumerian: "ĝeshtin", unicode: "\u{120FE}", english: "wine" },
  { sumerian: "ĝiri", unicode: "\u{1210C}", english: "foot" },
  { sumerian: "gu", unicode: "\u{12116}", english: "cord" },
  { sumerian: "gud", unicode: "\u{1211E}", english: "bull" },
  { sumerian: "gaz", unicode: "\u{12124}", english: "to kill" },
  { sumerian: "ig", unicode: "\u{12145}", english: "door" },
  { sumerian: "igi", unicode: "\u{12146}", english: "eye" },
  { sumerian: "im", unicode: "\u{1214E}", english: "rain" },
  { sumerian: "kush", unicode: "\u{12156}", english: "summer" },
  { sumerian: "gu", unicode: "\u{12165}", english: "to eat" },
  { sumerian: "naĝ", unicode: "\u{12158}", english: "to drink" },
  { sumerian: "kaskal", unicode: "\u{1219C}", english: "way" },
  { sumerian: "ku", unicode: "\u{121AA}", english: "place" },
  { sumerian: "numun", unicode: "\u{121B0}", english: "seed" },
  { sumerian: "lagab", unicode: "\u{121B8}", english: "block" },
  { sumerian: "li", unicode: "\u{121F7}", english: "branch" },
  { sumerian: "lu", unicode: "\u{121FD}", english: "person" },
  { sumerian: "lum", unicode: "\u{1221D}", english: "fruit" }
];

export default WORDS;
