const WORDS = [
  { sumerian: "a", unicode: "\u{12000}", english: "water" },
  { sumerian: "izi", unicode: "\u{12248}", english: "fire" },
  { sumerian: "mushen", unicode: "\u{12137}", english: "bird" },
  { sumerian: "erin", unicode: "\u{1209F}", english: "people" },
  { sumerian: "inim", unicode: "\u{12157}", english: "word" },
  { sumerian: "ki", unicode: "\u{121A0}", english: "place" },
  { sumerian: "an", unicode: "\u{1202D}", english: "sky" },
  { sumerian: "ĝesh", unicode: "\u{12111}", english: "tree" },
  { sumerian: "gi", unicode: "\u{12100}", english: "reed" },
  { sumerian: "ab", unicode: "\u{1200A}", english: "father" },
  { sumerian: "ak", unicode: "\u{1201D}", english: "to do" },
  { sumerian: "anshe", unicode: "\u{12032}", english: "donkey" },
  { sumerian: "arad", unicode: "\u{12034}", english: "slave" },
  { sumerian: "da", unicode: "\u{12055}", english: "line" },
  { sumerian: "dam", unicode: "\u{1206E}", english: "spouse" },
  { sumerian: "dara", unicode: "\u{12071}", english: "red" },
  { sumerian: "dab", unicode: "\u{12073}", english: "to seize" },
  { sumerian: "dim", unicode: "\u{12074}", english: "post" },
  { sumerian: "mun", unicode: "\u{12075}", english: "salt" },
  { sumerian: "du", unicode: "\u{1207A}", english: "to go" },
  { sumerian: "dub", unicode: "\u{1207E}", english: "tablet" },
  { sumerian: "e", unicode: "\u{1208D}", english: "house" },
  { sumerian: "eden", unicode: "\u{12094}", english: "back" },
  { sumerian: "en", unicode: "\u{12097}", english: "lord" },
  { sumerian: "ga", unicode: "\u{120B5}", english: "milk" },
  { sumerian: "ama", unicode: "\u{120BC}", english: "mother" },
  { sumerian: "gaba", unicode: "\u{120EE}", english: "chest" },
  { sumerian: "gal", unicode: "\u{120F2}", english: "big" },
  { sumerian: "ninda", unicode: "\u{120FB}", english: "bread" },
  { sumerian: "ĝeshtin", unicode: "\u{120FE}", english: "wine" },
  { sumerian: "ĝiri", unicode: "\u{1210C}", english: "foot" },
  { sumerian: "gu", unicode: "\u{12116}", english: "cord" },
  { sumerian: "gud", unicode: "\u{1211E}", english: "bull" },
  { sumerian: "gaz", unicode: "\u{12124}", english: "to kill" },
  { sumerian: "ig", unicode: "\u{12145}", english: "door" },
  { sumerian: "igi", unicode: "\u{12146}", english: "eye" },
  { sumerian: "im", unicode: "\u{1214E}", english: "rain" },
  { sumerian: "kush", unicode: "\u{12156}", english: "summer" },
  { sumerian: "gu", unicode: "\u{12165}", english: "to eat" },
  { sumerian: "naĝ", unicode: "\u{12158}", english: "to drink" },
  { sumerian: "kaskal", unicode: "\u{1219C}", english: "way" },
  { sumerian: "ku", unicode: "\u{121AA}", english: "to place" },
  { sumerian: "numun", unicode: "\u{121B0}", english: "seed" },
  { sumerian: "lagab", unicode: "\u{121B8}", english: "block" },
  { sumerian: "li", unicode: "\u{121F7}", english: "branch" },
  { sumerian: "lu", unicode: "\u{121FD}", english: "person" },
  { sumerian: "lum", unicode: "\u{1221D}", english: "fruit" },
  { sumerian: "ma", unicode: "\u{12223}", english: "ship" },
  { sumerian: "ĝi", unicode: "\u{1222A}", english: "night" },
  { sumerian: "mu", unicode: "\u{1222C}", english: "name" },
  { sumerian: "naĝa", unicode: "\u{12240}", english: "soap" },
  { sumerian: "nam", unicode: "\u{12246}", english: "fate" },
  { sumerian: "zal", unicode: "\u{1224C}", english: "to shine" },
  { sumerian: "ni", unicode: "\u{1224E}", english: "fear" },
  { sumerian: "nim", unicode: "\u{1224F}", english: "fly" },
  { sumerian: "piriĝ", unicode: "\u{1228A}", english: "lion" },
  { sumerian: "saĝ", unicode: "\u{12295}", english: "head" },
  { sumerian: "munus", unicode: "\u{122A9}", english: "woman" },
  { sumerian: "shag", unicode: "\u{122AE}", english: "heart" },
  { sumerian: "she", unicode: "\u{122BA}", english: "barley" },
  { sumerian: "shesh", unicode: "\u{122C0}", english: "brother" },
  { sumerian: "shu", unicode: "\u{122D7}", english: "hand" },
  { sumerian: "sheg", unicode: "\u{122DE}", english: "brick" },
  { sumerian: "siki", unicode: "\u{122E0}", english: "hair" },
  { sumerian: "shum", unicode: "\u{122E7}", english: "to give" },
  { sumerian: "tag", unicode: "\u{122F3}", english: "to touch" },
  { sumerian: "tar", unicode: "\u{122FB}", english: "to cut" },
  { sumerian: "te", unicode: "\u{122FC}", english: "cheek" },
  { sumerian: "til", unicode: "\u{122FE}", english: "to live" },
  { sumerian: "tu", unicode: "\u{12305}", english: "priest" },
  { sumerian: "ib", unicode: "\u{12308}", english: "angry" },
  { sumerian: "dumu", unicode: "\u{12309}", english: "child" },
  { sumerian: "ul", unicode: "\u{1230C}", english: "distant" },
  { sumerian: "ud", unicode: "\u{12313}", english: "day" },
  { sumerian: "itud", unicode: "\u{12317}", english: "moon" },
  { sumerian: "ur", unicode: "\u{12328}", english: "dog" },
  { sumerian: "uri", unicode: "\u{12335}", english: "vessel" },
  { sumerian: "iri", unicode: "\u{12337}", english: "city" },
  { sumerian: "urud", unicode: "\u{1234F}", english: "copper" },
  { sumerian: "uzud", unicode: "\u{1235A}", english: "goat" },
  { sumerian: "za", unicode: "\u{1235D}", english: "bead" },
  { sumerian: "zi", unicode: "\u{12363}", english: "life" },
  { sumerian: "kug", unicode: "\u{121AC}", english: "metal" }
];

export default WORDS;
